services:
  - type: web
    name: guru-pjok-kbb-api-dev
    runtime: python
    rootDir: backend
    plan: free
    branch: develop
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: development
      - key: DB_NAME
        value: guru_pjok_kbb_dev
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
